### ISSUE TITLE
Impossible to add attributions to a json style map

### ISSUE THREAD

**Issue by bruhnild** [Terralego/TerraVisu#313]
I tried to add attributions to a json style : https://viglino.github.io/geoservice-style/mapart/mapart.json but it do not appear on the map

Select **MapArt** in the layer's style : https://demo-terravisu.solutions-territoriales.fr/visualiser/toulouse#map=14.1/43.59723/1.43902

![image](https://github.com/Terralego/TerraVisu/assets/26433045/6d38a7d0-a3db-4593-adad-6168269b9856)

The attributions in the admin :  `<p>Map tiles by <a href="https://www.geoportail.gouv.fr/">Geoportail</a>, @ IGN-France<a href="https://www.ign.fr/">CC BY 3.0.</a> </p>`

![image](https://github.com/Terralego/TerraVisu/assets/26433045/5c66506f-db12-4b74-bc0d-e3e1b751ea65)

**Comment by submarcos** [comment]
You cant set attribution on existing tilejson. In case if mapbox tilejson URL, json should have its own attribution. Only way is to publish Somewhere your own json with attribution set and use its URL
