### ISSUE TITLE
Bug : unable to import data after Docker installation

### ISSUE THREAD

**Issue by ghatt38** [Terralego/TerraVisu#630]
Hello,
after installing Terravisu with Docker, following the steps on the https://terravisu.readthedocs.io/en/2024.02.7/ page, I'm having a problem importing data in any format. The message displayed is as follows and I don't know how to correct the problem:

Rapport global
method: refresh_data,exc_type: Exception,exc_message: ['<urllib3.connection.HTTPConnection object at 0x7f03383a4f10>: Failed to establish a new connection: [Errno 111] Connection refused'],

Thank you in advance for your help.
G. Hatt

**Comment by submarcos** [comment]
Hi @ghatt38 

I suppose that Elastic search docker container not start correctly.

Take a look to https://terravisu.readthedocs.io/en/stable/installation_configuration/troubleshooting.html#elastic-search-container-doesn-t-start

You have to set some settings to run it correctly

**Comment by ghatt38** [comment]
Hello,
thank you, the problem has been solved by following your advice.
Best regards,
G. Hatt
